language: node_js
git:
  depth: false

dist: trusty
sudo: required

services:
  - docker

branches:
  only:
    - master

matrix:
  include:
    - node_js: 8
      env: TEST_SUITE=unit
      install:
        - npm i
        - npm i -g codecov
      script:
        - npm run test:unit-ci
      after_success:
        - codecov

    - node_js: 8
      env: TEST_SUITE=lint
      install: npm i
      script: npm run lint

    - node_js: 8
      env: TEST_SUITE=screenshots
      before_install:
        - docker build -t screenshots .
        - docker ps -a
        - docker run -it --rm --cap-add=SYS_ADMIN -e MDC_GCLOUD_SERVICE_ACCOUNT_KEY="${MDC_GCLOUD_SERVICE_ACCOUNT_KEY}" screenshots /bin/sh
      script:
        - ./test/screenshot/start.sh
        - sleep 200s
        - npm run test:image-diff
